
package com.idea.store.sim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * 
 * 				 return namemethd(arg) throws tns:SimFaultMessage
 * 			
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimWebservice", targetNamespace = "http://www.store.idea.com/sim")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimWebservice {


    /**
     * 
     * @param psim
     * @return
     *     returns com.idea.store.sim.Sim
     * @throws SimFaultMessageException
     */
    @WebMethod(action = "http://www.store.idea.com/sim/findSimById")
    @WebResult(name = "findSimResponse", targetNamespace = "http://www.store.idea.com/sim", partName = "return")
    public Sim findSimById(
        @WebParam(name = "findSimRequest", targetNamespace = "http://www.store.idea.com/sim", partName = "psim")
        String psim)
        throws SimFaultMessageException
    ;

    /**
     * 
     * @param psim
     * @return
     *     returns com.idea.store.sim.SimList
     */
    @WebMethod(action = "http://www.store.idea.com/sim/findAllSims")
    @WebResult(name = "findAllSimsResponse", targetNamespace = "http://www.store.idea.com/sim", partName = "return")
    public SimList findAllSims(
        @WebParam(name = "findAllSimsRequest", targetNamespace = "http://www.store.idea.com/sim", partName = "psim")
        Void psim);

}
